### ISSUE TITLE
Update Homebrew Cask URL

### ISSUE THREAD

**Issue by reitermarkus** [SamirTalwar/monospacedmonologues.com#1]
Hi, we just wanted to let you know that you are still linking to the old Homebrew Cask homepage (`caskroom.io`) in [`2016-02-22--docker-part-one--getting-started.md`](https://github.com/SamirTalwar/monospacedmonologues.com/blob/45fe78c7a498de8939b71e5418b4f93e500b9243/content/posts/2016-02-22--docker-part-one--getting-started.md). This domain expired a few years ago and is not controlled by Homebrew anymore.

When you get a chance, please update the link to https://brew.sh/ or https://formulae.brew.sh/cask/.

Thank you,
the Homebrew team.

**Comment by SamirTalwar** [comment]
Done. Thanks for letting me know! I doubt anyone is reading that any more, but I appreciate your diligence.
